/ros2_imu_node:
  ros__parameters:
    imu:
      # mode zyz/atk
      module: "atk"
      # IMU端口
      port: "/dev/ttyAMA2"
      # 波特率 230400
      baudrate: 115200
      # 中断脚
      interupt:
        chip: ""
        line: -1
    # 1帧数据长度
    data_len: 121
    # 话题名称
    topic: "imu_data"
    # frame_id
    imu_frame_id: "imu_link"